apiVersion: v1
kind: ReplicationController
metadeta:
  name: myapp-rc
  labels:
    env: dev
    appname: demorc
spec:
  template:
    metadata:
      name: myapp_pod
      labels:
        name: app
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3