apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-monitoring-agent
spec:
  selector:
    matchLabels:
      app: my-monitoring-agent
  template:
    metadata:
      labels:
        app: my-monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: checkmk
        
