apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      env: dev
